name: Update AIR_SIGMETs

on:
  pull_request:
    paths:
      - "metgeojson.py"
      - ".github/workflows/update.yml"
    branches: [ "main" ]
  schedule:
    - cron:  '5 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: update
      run: |
       python3 metgeojson.py
    - name: commit
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "update AIRMETs and SIGMETs"
        git push